spring:
  application:
    name: ai-text-intelligence-dashboard
  ai:
    openai:
      api-key: ${OPENAI_KEY}
      chat:
        options:
          model: gpt-4o
          temperature: 0.0

app:
  llm:
    fallback-model: gpt-4o-mini

server:
  port: 8080
